name: ramblelust-deploy
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
      - name: Build
        run: |
          gem install jekyll bundler
          cd ramblelust.savageinter.net
          bundle
          bundle exec jekyll build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ramblelust.savageinter.net/_site
